export const PLANET_DEFINITIONS = [
  {
    id: 'mercury',
    name: 'Mercury',
    bodyName: 'Mercury',
    color: '#a3a3a3',
    radiusKm: 2439.7,
    axisTiltDeg: 0.034,
    summary: 'The smallest planet and the closest to the Sun.',
    education: [
      'Mercury has the shortest year in the Solar System: 88 Earth days.',
      'It has almost no atmosphere, so temperatures swing dramatically between day and night.',
      'Because it is so close to the Sun, Mercury is best seen during twilight near the horizon.',
    ],
    facts: {
      'Average distance from Sun': '0.39 AU',
      'Length of day': '58.6 Earth days',
      'Length of year': '88 Earth days',
      Moons: '0',
    },
    apodKeywords: ['mercury', 'messenger', 'bepiColombo', 'caloris'],
  },
  {
    id: 'venus',
    name: 'Venus',
    bodyName: 'Venus',
    color: '#e6c07b',
    radiusKm: 6051.8,
    axisTiltDeg: 177.4,
    summary: 'Earth’s near-twin in size with a runaway greenhouse atmosphere.',
    education: [
      'Venus is the hottest planet due to its thick carbon dioxide atmosphere.',
      'Its clouds are made of sulfuric acid droplets, hiding the surface from view in visible light.',
      'Venus rotates very slowly and in the opposite direction of most planets (retrograde rotation).',
    ],
    facts: {
      'Average distance from Sun': '0.72 AU',
      'Length of day': '243 Earth days',
      'Length of year': '225 Earth days',
      Moons: '0',
    },
    apodKeywords: ['venus', 'venera', 'magellan', 'akatsuki'],
  },
  {
    id: 'earth',
    name: 'Earth',
    bodyName: 'Earth',
    color: '#4aa3ff',
    radiusKm: 6371,
    axisTiltDeg: 23.44,
    summary: 'Our home world: oceans, continents, and a protective atmosphere.',
    education: [
      'Earth is the only known world with stable surface liquid water and life.',
      'Its atmosphere and magnetic field help shield the surface from solar radiation.',
      'Earth’s Moon stabilizes our axial tilt, contributing to long-term climate stability.',
    ],
    facts: {
      'Average distance from Sun': '1.00 AU',
      'Length of day': '24 hours',
      'Length of year': '365.25 days',
      Moons: '1',
    },
    apodKeywords: ['earth', 'terra', 'blue marble', 'aurora', 'iss', 'international space station'],
  },
  {
    id: 'mars',
    name: 'Mars',
    bodyName: 'Mars',
    color: '#d46a4c',
    radiusKm: 3389.5,
    axisTiltDeg: 25.19,
    summary: 'A cold desert world with giant volcanoes and ancient river valleys.',
    education: [
      'Mars has the largest volcano in the Solar System: Olympus Mons.',
      'Its thin atmosphere is mostly carbon dioxide and can’t retain much heat.',
      'Robotic explorers study Mars for clues about past habitability and water.',
    ],
    facts: {
      'Average distance from Sun': '1.52 AU',
      'Length of day': '24.6 hours',
      'Length of year': '687 Earth days',
      Moons: '2 (Phobos, Deimos)',
    },
    apodKeywords: ['mars', 'curiosity', 'perseverance', 'ingenuity', 'phobos', 'deimos'],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    bodyName: 'Jupiter',
    color: '#d7b594',
    radiusKm: 69911,
    axisTiltDeg: 3.13,
    summary: 'The largest planet, a gas giant with powerful storms and many moons.',
    education: [
      'Jupiter’s Great Red Spot is a storm larger than Earth that has raged for centuries.',
      'Its strong gravity shapes asteroid orbits and influences the architecture of the Solar System.',
      'The four largest moons—Io, Europa, Ganymede, Callisto—are visible in small telescopes.',
    ],
    facts: {
      'Average distance from Sun': '5.20 AU',
      'Length of day': '9.9 hours',
      'Length of year': '11.9 Earth years',
      Moons: '90+',
    },
    apodKeywords: ['jupiter', 'juno', 'galilean', 'europa', 'io', 'ganymede', 'callisto'],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    bodyName: 'Saturn',
    color: '#e8d9a8',
    radiusKm: 58232,
    axisTiltDeg: 26.73,
    summary: 'A gas giant famous for its spectacular ring system.',
    education: [
      'Saturn’s rings are made of countless particles of ice and rock.',
      'The moon Titan has a thick atmosphere and lakes of liquid methane and ethane.',
      'Cassini revealed complex ring dynamics and active geology on moons like Enceladus.',
    ],
    facts: {
      'Average distance from Sun': '9.58 AU',
      'Length of day': '10.7 hours',
      'Length of year': '29.5 Earth years',
      Moons: '80+',
    },
    apodKeywords: ['saturn', 'cassini', 'rings', 'titan', 'enceladus'],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    bodyName: 'Uranus',
    color: '#79d0d4',
    radiusKm: 25362,
    axisTiltDeg: 97.77,
    summary: 'An ice giant tipped on its side with an extreme axial tilt.',
    education: [
      'Uranus rotates “on its side,” giving it unusually extreme seasons.',
      'Methane in the atmosphere absorbs red light, giving Uranus its blue-green color.',
      'It has faint rings and many moons discovered by telescopes and spacecraft.',
    ],
    facts: {
      'Average distance from Sun': '19.2 AU',
      'Length of day': '17.2 hours',
      'Length of year': '84 Earth years',
      Moons: '27',
    },
    apodKeywords: ['uranus', 'voyager', 'rings', 'ice giant'],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    bodyName: 'Neptune',
    color: '#4b6cff',
    radiusKm: 24622,
    axisTiltDeg: 28.32,
    summary: 'A distant ice giant with strong winds and dark storms.',
    education: [
      'Neptune has some of the fastest winds in the Solar System.',
      'It was discovered through math: its gravity explained irregularities in Uranus’ orbit.',
      'The moon Triton orbits backward and may be a captured Kuiper Belt object.',
    ],
    facts: {
      'Average distance from Sun': '30.1 AU',
      'Length of day': '16.1 hours',
      'Length of year': '165 Earth years',
      Moons: '14',
    },
    apodKeywords: ['neptune', 'voyager', 'triton', 'ice giant'],
  },
]

export const MOON_DEFINITION = {
  id: 'moon',
  name: 'Moon',
  bodyName: 'Moon',
  color: '#cfd3d8',
  radiusKm: 1737.4,
  summary: 'Earth’s natural satellite that drives tides and lights our nights.',
  education: [
    'The Moon’s phases come from how sunlight hits its surface as it orbits Earth.',
    'Its gravitational pull raises tides and slowly changes Earth’s rotation rate over time.',
    'Apollo missions returned rocks that help reveal the early history of the Earth–Moon system.',
  ],
  facts: {
    'Average distance from Earth': '384,400 km',
    'Orbital period': '27.3 days (sidereal)',
    'Synodic month': '29.5 days (phase cycle)',
  },
  apodKeywords: ['moon', 'lunar', 'apollo', 'eclipse', 'crescent', 'full moon'],
}

export const METEOR_SHOWERS = [
  { id: 'quadrantids', name: 'Quadrantids', peakMonth: 1, peakDay: 4 },
  { id: 'lyrids', name: 'Lyrids', peakMonth: 4, peakDay: 22 },
  { id: 'eta-aquariids', name: 'Eta Aquariids', peakMonth: 5, peakDay: 6 },
  { id: 'perseids', name: 'Perseids', peakMonth: 8, peakDay: 12 },
  { id: 'orionids', name: 'Orionids', peakMonth: 10, peakDay: 21 },
  { id: 'leonids', name: 'Leonids', peakMonth: 11, peakDay: 17 },
  { id: 'geminids', name: 'Geminids', peakMonth: 12, peakDay: 14 },
  { id: 'ursids', name: 'Ursids', peakMonth: 12, peakDay: 22 },
]
